[package]
name = "nexus"
version = "0.1.0"
authors = ["Grunt Coder <gruntcoder@aethos.io>"]

[dependencies]
hyper = "0.12"
route-recognizer = "0.1.12"
log = "0.4"
pretty_env_logger = "0.2"
http = "0.1.6"
futures = "0.2.1"
