[package]
name = "nexus"
version = "0.1.0"
authors = ["Grunt Coder <gruntcoder@aethos.io>"]

[dependencies]
route-recognizer = "0.1.12"
log = "0.4.1"
pretty_env_logger = "0.2"
futures = "0.2.1"
rushttp = { git = "https://github.com/thejpster/rushttp" }
